[build]
  # Directory to change to before starting a build
  base = "."
  # Directory that contains the deploy-ready HTML files and assets
  publish = "build"
  # Default build command
  command = "npm run build"

[build.environment]
  # Node.js version to use
  NODE_VERSION = "18"

[[redirects]]
  # Redirect all routes to index.html for single-page app routing
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Security headers
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # Cache static assets
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
